services:
  app:
    image: gestion_toliboy_app:latest
    container_name: gestion_toliboy_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://tuservidor.com
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=toliboy
      - DB_USERNAME=toliboy
      - DB_PASSWORD=toliboy
    user: www-data
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: gestion_toliboy_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: gestion_toliboy_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: toliboy
      MYSQL_USER: toliboy
      MYSQL_PASSWORD: toliboy
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata_prod:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  dbdata_prod:
